// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("Customer")]
public partial class Customer
{
    public int Id { get; set; }

    [Key]
    [StringLength(24)]
    public string CustomerUuid { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [InverseProperty("CustomerUu")]
    public virtual ICollection<Site> Sites { get; set; } = new List<Site>();
}