// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

public partial class DataIntensiveDatabase1Context : DbContext
{
    public DataIntensiveDatabase1Context(DbContextOptions<DataIntensiveDatabase1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Device> Devices { get; set; }

    public virtual DbSet<Measurement> Measurements { get; set; }

    public virtual DbSet<Site> Sites { get; set; }

    public virtual DbSet<SiteUser> SiteUsers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerUuid).HasName("PK__Customer__B220AC2302B7C0C8");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Device>(entity =>
        {
            entity.HasKey(e => e.DeviceUuid).HasName("PK__Device__0D75D1D6B1ED4236");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.SiteUu).WithMany(p => p.Devices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Device_SiteUuid");
        });

        modelBuilder.Entity<Measurement>(entity =>
        {
            entity.HasKey(e => e.MeasurementUuid).HasName("PK__Measurem__DE038DE8178EEAF9");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.DeviceUu).WithMany(p => p.Measurements)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Measurement_DeviceUuid");
        });

        modelBuilder.Entity<Site>(entity =>
        {
            entity.HasKey(e => e.SiteUuid).HasName("PK__Site__26AA9DB68B484667");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.CustomerUu).WithMany(p => p.Sites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Site_CustomerUuid");
        });

        modelBuilder.Entity<SiteUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SiteUser__3214EC072B8A7D9B");

            entity.HasOne(d => d.SiteUu).WithMany(p => p.SiteUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Site_User_SiteUuid");

            entity.HasOne(d => d.UserUu).WithMany(p => p.SiteUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserUuid");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserUuid).HasName("PK__User__2DCB0AEB0A458DE3");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}