// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("Device")]
public partial class Device
{
    public int Id { get; set; }

    [Key]
    [StringLength(24)]
    public string DeviceUuid { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [Required]
    [StringLength(24)]
    public string SiteUuid { get; set; }

    [InverseProperty("DeviceUu")]
    public virtual ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();

    [ForeignKey("SiteUuid")]
    [InverseProperty("Devices")]
    public virtual Site SiteUu { get; set; }
}