// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("Measurement")]
public partial class Measurement
{
    public int Id { get; set; }

    [Key]
    [StringLength(24)]
    public string MeasurementUuid { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [Required]
    [StringLength(24)]
    public string DeviceUuid { get; set; }

    [Column("Measurement")]
    public double? Measurement1 { get; set; }

    [ForeignKey("DeviceUuid")]
    [InverseProperty("Measurements")]
    public virtual Device DeviceUu { get; set; }
}