// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("SiteUser")]
public partial class SiteUser
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(24)]
    public string UserUuid { get; set; }

    [Required]
    [StringLength(24)]
    public string SiteUuid { get; set; }

    [ForeignKey("SiteUuid")]
    [InverseProperty("SiteUsers")]
    public virtual Site SiteUu { get; set; }

    [ForeignKey("UserUuid")]
    [InverseProperty("SiteUsers")]
    public virtual User UserUu { get; set; }
}