// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("Site")]
public partial class Site
{
    public int Id { get; set; }

    [Key]
    [StringLength(24)]
    public string SiteUuid { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [Required]
    [StringLength(24)]
    public string CustomerUuid { get; set; }

    [ForeignKey("CustomerUuid")]
    [InverseProperty("Sites")]
    public virtual Customer CustomerUu { get; set; }

    [InverseProperty("SiteUu")]
    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();

    [InverseProperty("SiteUu")]
    public virtual ICollection<SiteUser> SiteUsers { get; set; } = new List<SiteUser>();
}