// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataIntensiveWepApi.Models;

[Table("User")]
public partial class User
{
    public int Id { get; set; }

    [Key]
    [StringLength(24)]
    public string UserUuid { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [InverseProperty("UserUu")]
    public virtual ICollection<SiteUser> SiteUsers { get; set; } = new List<SiteUser>();
}